name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go mod init cli/main.go
    
    - name: Get tidy
      run: go mod tidy

    - name: Build Linux amd64
      run: GOOS=linux GOARCH=amd64 go build -v -o build/cachet_monitor_linux_amd64 cli/main.go

    - name: Upload cachet_monitor_linux_amd64
      uses: actions/upload-artifact@v2
      with:
        name: cachet_monitor_linux_amd64
        path: build/cachet_monitor_linux_amd64